service: coffee-shop-api

frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

# Load modularized configurations
custom:
  tableName: ${self:service}-orders-${opt:stage, 'dev'}
  config: ${file(./config/provider.yml)}
  functions: ${file(./config/functions.yml)}
  resources: ${file(./config/resources.yml)}

provider: ${self:custom.config.provider}
functions: ${self:custom.functions.functions}
resources: ${self:custom.resources.resources}
