name: Deploy Coffee Shop API

on:
  push:
    branches:
      - master

jobs:
  deploy-dev-and-test:
    uses: ./.github/workflows/ci-setup.yml
    with:
      stage: dev
    secrets: inherit

  deploy-prod:
    uses: ./.github/workflows/ci-setup.yml
    needs: deploy-dev-and-test
    if: github.ref == 'refs/heads/master'
    with:
      stage: prod
    secrets: inherit
